version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      #      - cluster.name=es-docker-cluster
      #      - discovery.seed_hosts=es02,es03
      #      - cluster.initial_master_nodes=es01,es02,es03
      #      - discovery.seed_hosts=es02,es03
      #      - cluster.initial_master_nodes=es01,es02,es03
      #      - bootstrap.memory_lock=true
      #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/data/dev/es_data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    extra_hosts:
      - somehost:0.0.0.0
      - host1:127.0.0.1
    networks:
      - elastic
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
#    container_name: es02
#    environment:
#      - node.name=es02
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data02:/usr/share/elasticsearch/data
#    networks:
#      - elastic
#  es03:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
#    container_name: es03
#    environment:
#      - node.name=es03
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es02
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data03:/usr/share/elasticsearch/data
#    networks:
#      - elastic

volumes:
  data01:
    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local

networks:
  elastic:
    driver: bridge